### ISSUE TITLE
Can't change the default `.cursors` path

### ISSUE THREAD

**Issue by timfayz** [erf/vis-cursors#2]
Hi there.
Looks like knowing Lua is assumed when you start experiencing Vis. However I'm not the case :( 
There is written you can set the `module.path` variable if you want to change defaults. Good. But I didn't find the way how to fit that `module.path` variable.

In my `visrc.lua` file I had the following:
```
require('vis')
require('ctags')
require('vis-commentary')

require('cursors')

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
    vis:command("set numbers")
    vis:command("set autoindent")
    vis:command("set expandtab")
    vis:command("set tabwidth 4")
    vis:command("set show-tabs")
    vis:command("set cursorline")
end)
```

Can you hint how to fit that `module.path`, please?

**Comment by erf** [comment]
Hi, just set the path variable to the imported `cursors` module like this:
```
require('cursors').path = "some/path/file"
```
