### ISSUE TITLE
Support XDG Base Directory

### ISSUE THREAD

**Issue by SZanko** [erf/vis-cursors#5]
Could you please support XDG Base Directory by freedesktop.org?

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by erf** [comment]
Do you recommed defaulting to `XDG_CACHE_HOME`, like `$HOME/.cache/cursor`?

Do i then create the folder if it does not exists?

You know you can config the path in your visrc.lua ?

**Comment by SZanko** [comment]
1. Yes I would recommend that place
2. No the user have to specify an environment variable named `XDG_CACHE_HOME`
3. Yes I know but I think it would be nice for people how prefer a clean `$HOME` directory after the XDG Base Directory Specification

**Comment by erf** [comment]
Does the latest commit work for you?

**Comment by SZanko** [comment]
Yes, it works, thank you for the fast fixing of the "problem"

**Comment by erf** [comment]
Great, no problem
